name: "Feature request"
description: "Request a new feature or improvement for NexaSDK"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve NexaSDK 🙌

        Use this template for concrete improvements to the SDK.

  - type: checkboxes
    id: checks
    attributes:
      label: "Pre-checks"
      options:
        - label: "I searched existing issues and discussions"
          required: true

  - type: textarea
    id: problem
    attributes:
      label: "What problem are you trying to solve?"
      description: "Describe your use case and what’s painful today."
      placeholder: |
        I’m building X (e.g. local copilot on Snapdragon PC) and I’m blocked by Y in NexaSDK.
      render: text
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "What would you like NexaSDK to do?"
      description: "Describe your ideal solution (APIs, CLI flags, configs, etc.)."
      placeholder: |
        Example:
        - Add a `nexa run --backend npu` option that ...
        - Provide a Python helper `nexa.auto_backend(...)` that ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives you've considered"
      description: "Workarounds or other tools you’ve tried."
      placeholder: |
        I can currently do this by ..., but it’s slow / complex / fragile.
      render: text

  - type: textarea
    id: impact
    attributes:
      label: "Who does this help, and how much?"
      description: "Rough sense of impact (devx, perf, device coverage, etc.)."
      placeholder: |
        This would be useful for all Windows NPU developers using NexaSDK because ...
      render: text

  - type: textarea
    id: extra
    attributes:
      label: "Additional context"
      description: "Links, mock APIs, diagrams, prior art, etc."
      render: markdown
