#!/bin/sh

echo "Creating symbolic links for Nexa CLI..."

APP_PATH="/Applications/NexaCLI.app"
BIN_DIR="/usr/local/bin"

if [ ! -d "$BIN_DIR" ]; then
    mkdir -p "$BIN_DIR"
    chown root:wheel "$BIN_DIR"
    chmod 755 "$BIN_DIR"
fi

ln -sf "${APP_PATH}/Contents/Resources/nexa" "${BIN_DIR}/nexa"

exit 0