name: Build Nexa Executables MacOS CPU and Metal Bundles

on:
  push:
    branches: [ perry/macos-metal ]
  pull_request:
    branches: [ perry/macos-metal ]
  workflow_dispatch:

jobs:
  build-macos-cpu:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install cmake
    
    - name: Create and activate virtual environment
      run: |
        python -m venv env_cpu
        source env_cpu/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller wheel setuptools scikit-build-core

    - name: Install nexaai
      run: pip install -e . --verbose --prefer-binary --index-url https://nexaai.github.io/nexa-sdk/whl/cpu --extra-index-url https://pypi.org/simple --no-cache-dir

    - name: Extract version
      run: |
        VERSION=$(python -c "import re; print(re.search(r'__version__\s*=\s*[\'\"](.*?)[\'\"]', open('nexa/__init__.py').read()).group(1))")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with PyInstaller
      run: pyinstaller nexa-macos-cpu.spec

    - name: Modify Info.plist
      run: |
        /usr/libexec/PlistBuddy -c "Set CFBundleExecutable nexa" "dist/nexa.app/Contents/Info.plist"
        /usr/libexec/PlistBuddy -c "Add LSUIElement string 1" "dist/nexa.app/Contents/Info.plist"

    - name: Set app icon
      run: |
        cp nexa-icon.icns dist/nexa.app/Contents/Resources/
        /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile nexa-icon" dist/nexa.app/Contents/Info.plist

    - name: Import Code Signing Certificates
      env:
        APP_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
        APP_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        INSTALLER_CERTIFICATE_BASE64: ${{ secrets.MACOS_INSTALLER_CERTIFICATE }}
        INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_INSTALLER_CERTIFICATE_PASSWORD }}
      run: |
        echo $APP_CERTIFICATE_BASE64 | base64 --decode > app_certificate.p12
        echo $INSTALLER_CERTIFICATE_BASE64 | base64 --decode > installer_certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import app_certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security import installer_certificate.p12 -k build.keychain -P $INSTALLER_CERTIFICATE_PASSWORD -T /usr/bin/productsign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

    - name: Sign the app
      env:
        APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      run: |
        # Sign nexa_launcher individually
        # codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/Frameworks/nexa/nexa_launcher"
        
        # Sign Python binaries
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/Resources/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/Resources/Python.framework/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/Frameworks/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/Frameworks/Python.framework/Python"

        # Sign all other components
        find "dist/nexa.app/Contents" -type f \( -name "*.so" -o -name "*.dylib" \) -exec codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" {} \;
        
        # Sign the main executable
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa.app/Contents/MacOS/nexa"
        
        # Sign the entire app bundle with --deep option
        codesign --force --options runtime --timestamp --deep -s "$APPLE_DEVELOPER_ID" "dist/nexa.app"
        
        # Verify the signature
        codesign -vvv --deep --strict "dist/nexa.app"

    - name: Rename and upload app
      run: |
        tar -czf nexa.tar.gz -C dist nexa.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: nexa-cpu-app
        path: nexa.tar.gz

  build-macos-metal:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install cmake

    - name: Create and activate virtual environment
      run: |
        python -m venv env_metal
        source env_metal/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller wheel setuptools scikit-build-core

    - name: Install nexaai
      run: CMAKE_ARGS="-DGGML_METAL=ON -DSD_METAL=ON" pip install -e . --prefer-binary --index-url https://nexaai.github.io/nexa-sdk/whl/metal --extra-index-url https://pypi.org/simple --no-cache-dir

    - name: Extract version
      run: |
        VERSION=$(python -c "import re; print(re.search(r'__version__\s*=\s*[\'\"](.*?)[\'\"]', open('nexa/__init__.py').read()).group(1))")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with PyInstaller
      run: pyinstaller nexa-macos-metal.spec

    - name: Modify Info.plist
      run: |
        /usr/libexec/PlistBuddy -c "Set CFBundleExecutable nexa-metal" "dist/nexa-metal.app/Contents/Info.plist"
        /usr/libexec/PlistBuddy -c "Add LSUIElement string 1" "dist/nexa-metal.app/Contents/Info.plist"

    - name: Set app icon
      run: |
        cp nexa-icon.icns dist/nexa-metal.app/Contents/Resources/
        /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile nexa-icon" dist/nexa-metal.app/Contents/Info.plist

    - name: Import Code Signing Certificates
      env:
        APP_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
        APP_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        INSTALLER_CERTIFICATE_BASE64: ${{ secrets.MACOS_INSTALLER_CERTIFICATE }}
        INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_INSTALLER_CERTIFICATE_PASSWORD }}
      run: |
        echo $APP_CERTIFICATE_BASE64 | base64 --decode > app_certificate.p12
        echo $INSTALLER_CERTIFICATE_BASE64 | base64 --decode > installer_certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import app_certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security import installer_certificate.p12 -k build.keychain -P $INSTALLER_CERTIFICATE_PASSWORD -T /usr/bin/productsign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

    - name: Sign the app
      env:
        APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      run: |        
        # Sign Python binaries
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app/Contents/Resources/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app/Contents/Resources/Python.framework/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app/Contents/Frameworks/Python"
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app/Contents/Frameworks/Python.framework/Python"

        # Sign all other components
        find "dist/nexa-metal.app/Contents" -type f \( -name "*.so" -o -name "*.dylib" \) -exec codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" {} \;
        
        # Sign the main executable
        codesign --force --options runtime --timestamp -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app/Contents/MacOS/nexa-metal"
        
        # Sign the entire app bundle with --deep option
        codesign --force --options runtime --timestamp --deep -s "$APPLE_DEVELOPER_ID" "dist/nexa-metal.app"
        
        # Verify the signature
        codesign -vvv --deep --strict "dist/nexa-metal.app"

    - name: Rename and upload app
      run: |
        tar -czf nexa-metal.tar.gz -C dist nexa-metal.app
      
    - uses: actions/upload-artifact@v4
      with:
        name: nexa-metal-app
        path: nexa-metal.tar.gz

  
  create-combined-pkg-installer:
    needs: [build-macos-cpu, build-macos-metal]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download CPU app
      uses: actions/download-artifact@v4
      with:
        name: nexa-cpu-app
        
    - name: Download Metal app
      uses: actions/download-artifact@v4
      with:
        name: nexa-metal-app

    - name: Extract apps
      run: |
        tar -xzf nexa.tar.gz
        tar -xzf nexa-metal.tar.gz

    - name: Extract version
      run: |
        VERSION=$(python -c "import re; print(re.search(r'__version__\s*=\s*[\'\"](.*?)[\'\"]', open('nexa/__init__.py').read()).group(1))")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Import Code Signing Certificates
      env:
        APP_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
        APP_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        INSTALLER_CERTIFICATE_BASE64: ${{ secrets.MACOS_INSTALLER_CERTIFICATE }}
        INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_INSTALLER_CERTIFICATE_PASSWORD }}
      run: |
        echo $APP_CERTIFICATE_BASE64 | base64 --decode > app_certificate.p12
        echo $INSTALLER_CERTIFICATE_BASE64 | base64 --decode > installer_certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import app_certificate.p12 -k build.keychain -P $APP_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security import installer_certificate.p12 -k build.keychain -P $INSTALLER_CERTIFICATE_PASSWORD -T /usr/bin/productsign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

    - name: Create PKG Installer
      run: |
        mkdir -p pkg_root/Applications pkg_scripts

        cp -R nexa.app pkg_root/Applications/
        cp -R nexa-metal.app pkg_root/Applications/

        cat << EOF > pkg_scripts/preinstall
        #!/bin/bash
        # Remove existing symlink if it exists
        rm -f /usr/local/bin/nexa
        # Remove existing Nexa app if it exists
        rm -rf /Applications/nexa.app
        exit 0
        EOF

        cat << EOF > pkg_scripts/postinstall
        #!/bin/bash
        # Determine if Metal is supported
        if /usr/sbin/system_profiler SPDisplaysDataType | grep -q "Metal: Supported"; then
          cp -R /Applications/nexa-metal.app /Applications/nexa.app
          rm -rf /Applications/nexa-metal.app
        else
          cp -R /Applications/nexa.app /Applications/nexa.app
          rm -rf /Applications/nexa.app
        fi

        # Create the symlink
        ln -sf /Applications/nexa.app/Contents/MacOS/nexa /usr/local/bin/nexa

        # Ensure the symlink is created successfully
        if [ -L "/usr/local/bin/nexa" ]; then
          echo "Symlink created successfully"
        else
          echo "Failed to create symlink"
          exit 1
        fi

        # Set correct permissions
        chown root:wheel /usr/local/bin/nexa
        chmod 755 /usr/local/bin/nexa

        exit 0
        EOF

        chmod +x pkg_scripts/preinstall pkg_scripts/postinstall

        pkgbuild --root pkg_root \
                --scripts pkg_scripts \
                --identifier com.nexaai.sdk \
                --version ${{ env.VERSION }} \
                --install-location / \
                "Nexa-${{ env.VERSION }}-unsigned.pkg"

        rm -rf pkg_root pkg_scripts

    - name: Sign PKG
      env:
        APPLE_INSTALLER_ID: ${{ secrets.APPLE_INSTALLER_ID }}
      run: |
        # Sign the package
        productsign --sign "$APPLE_INSTALLER_ID" \
                    "Nexa-${{ env.VERSION }}-unsigned.pkg" \
                    "Nexa-${{ env.VERSION }}.pkg"

        # Verify the signature
        pkgutil --check-signature "Nexa-${{ env.VERSION }}.pkg"

        # Remove the unsigned package
        rm "Nexa-${{ env.VERSION }}-unsigned.pkg"

    - name: Notarize PKG
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        echo "Submitting package for notarization..."
        NOTARIZATION_OUTPUT=$(xcrun notarytool submit "Nexa-${{ env.VERSION }}.pkg" --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$APPLE_TEAM_ID" --wait)
        echo "Submission output:"
        echo "$NOTARIZATION_OUTPUT"
        
        # Extract the submission ID (ensuring it's a single line)
        SUBMISSION_ID=$(echo "$NOTARIZATION_OUTPUT" | grep 'id:' | head -n 1 | awk '{print $2}' | tr -d '\n')
        echo "Extracted Submission ID: $SUBMISSION_ID"
        
        if [ -z "$SUBMISSION_ID" ]; then
          echo "Failed to extract submission ID. Notarization likely failed."
          exit 1
        fi
        
        # Wait for notarization to complete and check the result
        while true; do
          NOTARIZATION_INFO=$(xcrun notarytool info "$SUBMISSION_ID" --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$APPLE_TEAM_ID")
          STATUS=$(echo "$NOTARIZATION_INFO" | grep "status:" | cut -d: -f2 | xargs)
          echo "Notarization status: $STATUS"
          
          if [ "$STATUS" = "Accepted" ]; then
            echo "Notarization successful"
            echo "Stapling notarization ticket to the package..."
            xcrun stapler staple "Nexa-${{ env.VERSION }}.pkg"
            echo "Notarization ticket stapled to the package"
            break
          elif [ "$STATUS" = "Invalid" ] || [ "$STATUS" = "Rejected" ]; then
            echo "Notarization failed. Fetching detailed log..."
            xcrun notarytool log "$SUBMISSION_ID" --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$APPLE_TEAM_ID"
            echo "Notarization failed. See log above for details."
            exit 1
          fi
          
          echo "Waiting for 30 seconds before checking again..."
          sleep 30
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nexa-${{ env.VERSION }}-macos-installer
        path: Nexa-${{ env.VERSION }}.pkg